# Generated by Django 5.1.6 on 2025-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_address_remove_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakersize',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
