# Generated by Django 5.1.6 on 2025-06-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sneakersize_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sneakersize'),
        ),
    ]
