# Generated by Django 5.1.6 on 2025-07-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sneakers/'),
        ),
    ]
