# Generated by Django 5.1.6 on 2025-07-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sneaker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='image',
        ),
    ]
