# Generated by Django 5.1.6 on 2025-07-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_is_verified_customer_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('created', 'Order Created'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed')], default='created', max_length=20),
        ),
    ]
